Свойство 1. Дважды транспонированная матрица равна исходной матрице:

In [29]:
import numpy as np
A = np.matrix('10 5 7; 13 22 4')
print(A)
R = (A.T).T
print(R)

[[10  5  7]
 [13 22  4]]
[[10  5  7]
 [13 22  4]]


Свойство 2. Транспонирование суммы матриц равно сумме транспонированных матриц:

In [3]:
A = np.matrix('10 5 7; 13 22 4')
B = np.matrix('0 11 3; 9 1 15')
L = (A + B).T
R = A.T + B.T
print(L)
print(R)

[[10 22]
 [16 23]
 [10 19]]
[[10 22]
 [16 23]
 [10 19]]


Свойство 3. Транспонирование произведения матриц равно произведению транспонированных
матриц расставленных в обратном порядке:

In [5]:
A = np.matrix('10 5 ; 13 22')
B = np.matrix('0 11 ; 9 1')
L = (A.dot(B)).T
R = (B.T).dot(A.T)
print(L)
print(R)

[[ 45 198]
 [115 165]]
[[ 45 198]
 [115 165]]


Свойство 4. Транспонирование произведения матрицы на число равно произведению этого
числа на транспонированную матрицу:

In [6]:
A = np.matrix('10 5 7; 13 22 4')
k = 7
L = (k * A).T
R = k * (A.T)
print(L)
print(R)

[[ 70  91]
 [ 35 154]
 [ 49  28]]
[[ 70  91]
 [ 35 154]
 [ 49  28]]


Свойство 5. Определители исходной и транспонированной матрицы совпадают:

In [7]:
A = np.matrix('10 5 ; 13 22')
A_det = np.linalg.det(A)
A_T_det = np.linalg.det(A.T)
print(format(A_det, '.9g'))
print(format(A_T_det, '.9g'))

155
155


Свойство 6. Произведение единицы и любой заданной матрицы равно заданной матрице:

In [8]:
A = np.matrix('10 5 ; 13 22')
L = 1 * A
R = A
print(L)
print(R)

[[10  5]
 [13 22]]
[[10  5]
 [13 22]]


Свойство 7. Произведение нуля и любой матрицы равно нулевой матрице, размерность которой
равна исходной матрицы:

In [10]:
A = np.matrix('10 5 ; 13 22')
B = np.matrix('0 0 ; 0 0')
L = 0 * A
R = B
print(L)
print(R)

[[0 0]
 [0 0]]
[[0 0]
 [0 0]]


Свойство 8. Произведение матрицы на сумму чисел равно сумме произведений матрицы на
каждое из этих чисел:

In [11]:
A = np.matrix('10 5 ; 13 22')
p = 2
q = 3
L = (p + q) * A
R = p * A + q * A
print(L)
print(R)

[[ 50  25]
 [ 65 110]]
[[ 50  25]
 [ 65 110]]


Свойство 9. Произведение матрицы на произведение двух чисел равно произведению второго
числа и заданной матрицы, умноженному на первое число:

In [12]:
A = np.matrix('10 5 ; 13 22')
p = 2
q = 3
L = (p * q) * A
R = p * (q * A)
print(L)
print(R)

[[ 60  30]
 [ 78 132]]
[[ 60  30]
 [ 78 132]]


Свойство 10. Коммутативность сложения. От перестановки матриц их сумма не изменяется:

In [13]:
A = np.matrix('10 5 ; 13 22')
B = np.matrix('0 11 ; 9 1')
L = A + B
R = B + A
print(L)
print(R)

[[10 16]
 [22 23]]
[[10 16]
 [22 23]]


Свойство 11. Ассоциативность сложения. Результат сложения трех и более матриц не зависит от
порядка, в котором эта операция будет выполняться:

In [14]:
A = np.matrix('10 5 ; 13 22')
B = np.matrix('0 11 ; 9 1')
C = np.matrix('5 7 ; 19 20')
L = A + (B + C)
R = (A + B) + C
print(L)
print(R)

[[15 23]
 [41 43]]
[[15 23]
 [41 43]]


Свойство 12. Ассоциативность умножения. Результат умножения матриц не зависит от порядка, в
котором будет выполняться эта операция:

In [15]:
A = np.matrix('10 5 7; 13 22 4')
B = np.matrix('0 11 ; 9 1; 17 8')
C = A.dot(B)
print(C)

[[164 171]
 [266 197]]


In [16]:
A = np.matrix('10 5 ; 13 22')
B = np.matrix('0 11 ; 9 1')
C = np.matrix('5 7 ; 19 20')
L = A.dot(B.dot(C))
R = (A.dot(B)).dot(C)
print(L)
print(R)

[[2410 2615]
 [4125 4686]]
[[2410 2615]
 [4125 4686]]


Свойство 13. Дистрибутивность умножения. Произведение матрицы на сумму матриц равно
сумме произведений матриц:

In [18]:
A = np.matrix('10 5 ; 13 22')
B = np.matrix('0 11 ; 9 1')
C = np.matrix('5 7 ; 19 20')
L = A.dot(B + C)
R = A.dot(B) + A.dot(C)
print(L)
print(R)

[[190 285]
 [681 696]]
[[190 285]
 [681 696]]


Свойство 14. Если у матрицы есть строка или столбец, состоящие из нулей, то определитель
такой матрицы равен нулю:

In [21]:
A = np.matrix('8 -5 7; 6 -9 4; -1 8 2')
print(A)
np.linalg.det(A)

[[ 8 -5  7]
 [ 6 -9  4]
 [-1  8  2]]


-46.99999999999997

Свойство 15. Если все элементы строки или столбца матрицы умножить на какое-то число, то и
определитель будет умножен на это число:

In [22]:
A = np.matrix('8 -5 7; 6 -9 4; -1 8 2')
print(A)
k = 2
B = A.copy()
B[2, :] = k * B[2, :]
print(B)

[[ 8 -5  7]
 [ 6 -9  4]
 [-1  8  2]]
[[ 8 -5  7]
 [ 6 -9  4]
 [-2 16  4]]


In [23]:
det_A = round(np.linalg.det(A), 3)
det_B = round(np.linalg.det(B), 3)
print(det_A * k)
print(det_B)


-94.0
-94.0


Свойство 16. Если матрица содержит пропорциональные строки, то ее определитель равен нулю:

In [24]:
A = np.matrix('8 -5 7; 6 -9 4; -1 8 2')
print(A)
k = 2
A[1, :] = A[0, :] + k * A[2, :]
round(np.linalg.det(A), 3)

[[ 8 -5  7]
 [ 6 -9  4]
 [-1  8  2]]


0.0

Свойство 17. Обратная матрица обратной матрицы есть исходная матрица:

In [25]:
A = np.matrix('8 -5 7; 6 -9 4; -1 8 2')
A_inv = np.linalg.inv(A)
A_inv_inv = np.linalg.inv(A_inv)
print(A)
print(A_inv_inv)

[[ 8 -5  7]
 [ 6 -9  4]
 [-1  8  2]]
[[ 8. -5.  7.]
 [ 6. -9.  4.]
 [-1.  8.  2.]]
